joint_origins:
  joint1:
    parent: base_link
    child: link1
    origin_xyz: "0 0 0.096"
    origin_rpy: "0 0 3.1416"
  joint2:
    parent: link1
    child: link2
    origin_xyz: "0 0 0"
    origin_rpy: "1.5708 -1.5708 0"
  joint3:
    parent: link2
    child: link3
    origin_xyz: "0 0.418 0"
    origin_rpy: "0 0 1.10"
  joint4:
    parent: link3
    child: link4
    origin_xyz: "0.398 0 0.122"
    origin_rpy: "0 0 0"
  joint5:
    parent: link4
    child: link5
    origin_xyz: "0 0.098 0"
    origin_rpy: "1.5708 0 -3.1416"
  joint6:
    parent: link5
    child: link6
    origin_xyz: "0 -0.089 0"
    origin_rpy: "-1.5708 0 3.1416"
